DRAFT use onnx2circle for one-import-onnx
on-going draft to use onnx2circle for one-import-onnx and deprecate onnx-tf.

Signed-off-by: SaeHie Park <saehie.park@gmail.com>

diff --git a/compiler/one-cmds/one-prepare-venv b/compiler/one-cmds/one-prepare-venv
--- a/compiler/one-cmds/one-prepare-venv
+++ b/compiler/one-cmds/one-prepare-venv
@@ -69,9 +69,7 @@ VER_PROTOBUF=4.23.3
 VER_NUMPY=1.24.3
 
 echo "Setting version for '$DISTRIB_CODENAME'"
-if [[ "$DISTRIB_CODENAME" == "bionic" ]]; then
-  : # use as is
-elif [[ "$DISTRIB_CODENAME" == "focal" ]]; then
+if [[ "$DISTRIB_CODENAME" == "focal" ]]; then
   : # use as is
 elif [[ "$DISTRIB_CODENAME" == "jammy" ]]; then
   : # TODO change vesions
@@ -79,6 +77,32 @@ elif [[ "$DISTRIB_CODENAME" == "noble" ]]; then
   : # TODO change vesions
 else
   echo "Error one-prepare-venv: Unsupported codename $DISTRIB_CODENAME"
+  exit 1
+fi
+
+PYTHON_VER=$(${PYTHON3_EXEC} -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" )
+if [[ "$PYTHON_VER" == "3.10" ]]; then
+  VER_TENSORFLOW=2.19.0
+  VER_ONNX=1.18.0
+  VER_ONNXRUNTIME=1.21.1
+  VER_TORCH="2.7.0+cpu"
+  VER_NUMPY="1.26.4"
+  VER_PROTOBUF="5.29.4"
+  VER_TF_PROB=0
+  VER_TF_ADON=0
+  VER_ONNX_TF=0
+elif [[ "$PYTHON_VER" == "3.12" ]]; then
+  VER_TENSORFLOW=2.19.0
+  VER_ONNX=1.18.0
+  VER_ONNXRUNTIME=1.21.1
+  VER_TORCH="2.7.0+cpu"
+  VER_NUMPY="1.26.4"
+  VER_PROTOBUF="5.29.4"
+  VER_TF_PROB=0
+  VER_TF_ADON=0
+  VER_ONNX_TF=0
+else
+  echo "Error one-prepare-venv: Unsupported python $PYTHON_VER"
   exit 1
 fi
 
@@ -111,15 +135,22 @@ ${VENV_PYTHON} -m pip ${PIP_OPTIONS} install --upgrade pip setuptools
 
 PYTHON_PACKAGES="tensorflow-cpu==${VER_TENSORFLOW} "
 PYTHON_PACKAGES+="Pillow "
-PYTHON_PACKAGES+="tensorflow_probability==${VER_TF_PROB} "
-PYTHON_PACKAGES+="tensorflow_addons==${VER_TF_ADON} "
 PYTHON_PACKAGES+="torch==${VER_TORCH} "
 PYTHON_PACKAGES+="onnx==${VER_ONNX} "
 PYTHON_PACKAGES+="onnxruntime==${VER_ONNXRUNTIME} "
-PYTHON_PACKAGES+="onnx-tf==${VER_ONNX_TF} "
 PYTHON_PACKAGES+="protobuf==${VER_PROTOBUF} "
 PYTHON_PACKAGES+="fsspec==2024.6.1 "
 PYTHON_PACKAGES+="pydot==${VER_PYDOT} "
 PYTHON_PACKAGES+="numpy==${VER_NUMPY} "
+
+if [[ "${VER_TF_PROB}" != "0" ]]; then
+  PYTHON_PACKAGES+="tensorflow_probability==${VER_TF_PROB} "
+fi
+if [[ "${VER_TF_ADON}" != "0" ]]; then
+  PYTHON_PACKAGES+="tensorflow_addons==${VER_TF_ADON} "
+fi
+if [[ "${VER_ONNX_TF}" != "0" ]]; then
+  PYTHON_PACKAGES+="onnx-tf==${VER_ONNX_TF} "
+fi
 
 ${VENV_PYTHON} -m pip ${PIP_OPTIONS} install --upgrade ${PYTHON_PACKAGES} ${TORCH_SOURCE_OPTION}
