nnpkg-test can test list or all pkg in directory

diff --git a/tests/scripts/command/nnpkg-test b/tests/scripts/command/nnpkg-test
--- a/tests/scripts/command/nnpkg-test
+++ b/tests/scripts/command/nnpkg-test
@@ -3,7 +3,7 @@
 set -u
 
 command_exists() {
-	command -v "$@" > /dev/null 2>&1
+    command -v "$@" > /dev/null 2>&1
 }
 
 progname=$(basename "${BASH_SOURCE[0]}")
@@ -14,123 +14,143 @@ difftool=${difftool:-"h5diff"}
 delete_dumped_on_failure=0
 
 usage() {
-  echo "Usage: $progname [options] nnpackage_test"
-  echo "Run an nnpackage testcase"
-  echo ""
-  echo "Returns"
-  echo "     0       success"
-  echo "  non-zero   failure"
-  echo ""
-  echo "Options:"
-  echo "    -h   show this help"
-  echo "    -i   set input directory (default=$indir)"
-  echo "    -o   set output directory (default=$outdir)"
-  echo "    -d   delete dumped file on failure."
-  echo "         (dumped file are always deleted on success) (default=$delete_dumped_on_failure)"
-  echo ""
-  echo "Environment variables:"
-  echo "   nnpackage_run    path to nnpackage_run (default=Product/out/bin/nnpackage_run)"
-  echo "   difftool         path to i5diff or h5diff (default=h5diff)"
-  echo ""
-  echo "Examples:"
-  echo "    $progname Add_000                => run $indir/Add_000 and check output"
-  echo "    $progname -i nnpkg-tcs Add_000   => run nnpkg-tcs/Add_000 and check output"
-  exit 1
+    echo "Usage: $progname [options] nnpackage_test"
+    echo "Run an nnpackage testcase"
+    echo ""
+    echo "Returns"
+    echo "     0       success"
+    echo "  non-zero   failure"
+    echo ""
+    echo "Options:"
+    echo "    -h   show this help"
+    echo "    -i   set input directory (default=$indir)"
+    echo "    -o   set output directory (default=$outdir)"
+    echo "    -d   delete dumped file on failure."
+    echo "         (dumped file are always deleted on success) (default=$delete_dumped_on_failure)"
+    echo ""
+    echo "Environment variables:"
+    echo "   nnpackage_run    path to nnpackage_run (default=Product/out/bin/nnpackage_run)"
+    echo "   difftool         path to i5diff or h5diff (default=h5diff)"
+    echo ""
+    echo "Examples:"
+    echo "    $progname Add_000                => run $indir/Add_000 and check output"
+    echo "    $progname -i nnpkg-tcs Add_000   => run nnpkg-tcs/Add_000 and check output"
+    exit 1
 }
 
 if [ $# -eq 0 ]; then
-  echo "For help, type $progname -h"
-  exit 1
+    echo "For help, type $progname -h"
+    exit 1
 fi
 
-while getopts "hdi:o:" OPTION; do
+verbose=1
+while getopts "hdi:o:v" OPTION; do
 case "${OPTION}" in
     h) usage;;
     d) delete_dumped_on_failure=1;;
     i) indir=$OPTARG;;
     o) outdir=$OPTARG;;
+    v) verbose=0;;
     ?) exit 1;;
 esac
 done
 
 shift $((OPTIND-1))
 
-if [ $# -ne 1 ]; then
-  echo "error: wrong argument (no argument or too many arguments)."
-  echo "For help, type $progname -h"
-  exit 1
-fi
+find_tests()
+{
+    local TEST_DIRS="$@"
+    local TESTS_TO_RUN=""
 
-if [ ! -e Product ]; then
-  echo "error: please make sure to run this script in nnfw home."
-  exit 1
-fi
+    if [[ $# -eq 0 ]]; then
+        TEST_DIRS="."
+    fi
 
-tcname=$(basename "$1")
-nnpkg="$indir/$tcname"
+    #shift $#
+    for DIR in $TEST_DIRS; do
+        for entry in $indir/$DIR; do
+            if [ -d "$entry" ]; then
+                TESTS_FOUND=$(find "$entry" -type d -name metadata -exec dirname {} \;| sed 's|^./||' | sort)
+                TESTS_TO_RUN="$TESTS_TO_RUN $TESTS_FOUND"
+            else
+                echo "Test $entry was not found. This test is not added." 1>&2
+            fi
+        done
+    done
 
-# run
-
-if [ ! -e $nnpkg ]; then
-  echo "error: nnpackage "$nnpkg" does not exist."
-  exit 1
-fi
-
-if ! command_exists $nnpkg_run; then
-  echo "error: runner "$nnpkg_run" does not exist."
-  exit 1
-fi
-
-dumped="$outdir/$tcname".out.h5
-
-echo -n "[  Run  ] $nnpkg "
-
-if $nnpkg_run \
---nnpackage "$nnpkg" \
---load "$nnpkg/metadata/tc/input.h5" \
---dump "$dumped" >& /dev/null > "$dumped.log" 2>&1 ; then
-  echo -e "\tPass"
-  rm "$dumped.log"
-else
-  echo -e "\tFail"
-  echo ""
-  cat "$dumped.log"
-  echo ""
-  rm "$dumped.log"
-  exit 2
-fi
-
-# diff
-
-if ! command_exists $difftool; then
-  echo "error: difftool "$difftool" does not exist."
-  exit 1
-fi
-
-expected="$nnpkg/metadata/tc/expected.h5"
-
-echo -n "[Compare] $nnpkg "
+    echo $TESTS_TO_RUN
+}
 
 test_fail()
 {
-  echo -e "\tFail"
-  [ $delete_dumped_on_failure ] && rm "$dumped"
-  cat "$dumped.log"
-  rm "$dumped.log"
-  exit 3
+    echo -e "\tFail"
+    [ $delete_dumped_on_failure ] && rm "$dumped"
+    cat "$dumped.log"
+    rm "$dumped.log"
+    exit 3
 }
 
 test_pass()
 {
-  echo -e "\tPass"
-  cat "$dumped.log"
-  rm "$dumped" "$dumped.log"
+    echo -e "\tPass"
+    if [ $verbose -eq 0 ]; then
+      cat "$dumped.log"
+    fi
+    rm "$dumped" "$dumped.log"
 }
 
-if ! $difftool -d 0.001 -v "$dumped" "$expected" /value >& "$dumped.log"; then
-  test_fail
-elif grep "not comparable" "$dumped.log" > /dev/null; then
-  test_fail
-else
-  test_pass
-fi
+TESTS_TO_RUN=$(find_tests $@)
+for TEST_NAME in $TESTS_TO_RUN; do
+    tcname=$(basename "$TEST_NAME")
+    nnpkg="$indir/$tcname"
+
+    # run
+
+    if [ ! -e $nnpkg ]; then
+      echo "error: nnpackage "$nnpkg" does not exist."
+      exit 1
+    fi
+
+    if ! command_exists $nnpkg_run; then
+      echo "error: runner "$nnpkg_run" does not exist."
+      exit 1
+    fi
+
+    dumped="$outdir/$tcname".out.h5
+
+    echo -n "[  Run  ] $nnpkg "
+
+    if $nnpkg_run \
+    --nnpackage "$nnpkg" \
+    --load "$nnpkg/metadata/tc/input.h5" \
+    --dump "$dumped" >& /dev/null > "$dumped.log" 2>&1 ; then
+        echo -e "\tPass"
+        rm "$dumped.log"
+    else
+        echo -e "\tFail"
+        echo ""
+        cat "$dumped.log"
+        echo ""
+        rm "$dumped.log"
+        exit 2
+    fi
+
+    # diff
+
+    if ! command_exists $difftool; then
+        echo "error: difftool "$difftool" does not exist."
+        exit 1
+    fi
+
+    expected="$nnpkg/metadata/tc/expected.h5"
+
+    echo -n "[Compare] $nnpkg "
+
+    if ! $difftool -d 0.001 -v "$dumped" "$expected" /value >& "$dumped.log"; then
+        test_fail
+    elif grep "not comparable" "$dumped.log" > /dev/null; then
+        test_fail
+    else
+        test_pass
+    fi
+done
