[infra] Build docker image with ubuntu codename
Use ubuntu codename for docker build parameter
build-docker-image "--extension" parameter will be deprecated
Change dockerfile path by using ubuntu codename

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

diff --git a/infra/command/build-docker-image b/infra/command/build-docker-image
--- a/infra/command/build-docker-image
+++ b/infra/command/build-docker-image
@@ -5,15 +5,18 @@ function Usage()
   echo "Usage: $0 $(basename ${BASH_SOURCE[0]}) [OPTIONS]"
   echo ""
   echo "Options:"
-  echo "      --extension               dockerfile extension in infra/docker"
+  echo "      --extension               dockerfile extension in infra/docker (will be deprecated)"
+  echo "      --codename                ubuntu codename, default image name is nnfw/nnas:[codename]"
   echo "Options can use as docker build option:"
   docker build --help
 }
 
-DOCKER_FILE_RPATH_BASE="infra/docker/Dockerfile"
+DOCKER_FILE_RPATH_BASE="infra/docker"
 DOCKER_BUILD_ARGS=()
-DOCKER_FILE_RPATH=${DOCKER_FILE_RPATH_BASE}
-DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME:-nnfw/nnas}
+
+# Default setting
+UBUNTU_CODENAME="xenial"
+DOCKER_TAG="latest"
 
 while [[ $# -gt 0 ]]
 do
@@ -26,9 +29,19 @@ do
       exit 1
       ;;
     --extension)
-      DOCKER_FILE_RPATH="${DOCKER_FILE_RPATH_BASE}.$2"
+      if [[ $2 == "1804" ]]; then
+        UBUNTU_CODENAME="bionic"
+      else
+        echo "Invalid extension"
+        exit 1
+      fi
       shift
       shift
+      ;;
+    --codename)
+      UBUNTU_CODENAME=$2
+      DOCKER_TAG=$2
+      shift 2
       ;;
     -t|--tag)
       DOCKER_IMAGE_NAME="$2"
@@ -42,6 +55,8 @@ do
   esac
 done
 
+DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME:-nnfw/nnas:$DOCKER_TAG}
+DOCKER_FILE_RPATH=$DOCKER_FILE_RPATH_BASE/$UBUNTU_CODENAME/Dockerfile
 DOCKER_BUILD_ARGS+=("-t ${DOCKER_IMAGE_NAME}")
 
 docker build --build-arg http_proxy="${http_proxy}" \
