Find python3.10 first, then python3.x
ONE-DCO-1.0-Signed-off-by: Seungho Henry Park <shs.park@samsung.com>

diff --git a/circle-mlir/infra/overlay/prepare-venv b/circle-mlir/infra/overlay/prepare-venv
--- a/circle-mlir/infra/overlay/prepare-venv
+++ b/circle-mlir/infra/overlay/prepare-venv
@@ -31,14 +31,19 @@ VENV_PYTHON=${DRIVER_PATH}/${VENV_NAME}/bin/python
 PYTHON_REQUIRED_MAJOR=3
 PYTHON_REQUIRED_MINOR=10
 
-PYTHON_BIN=$(which python3)
+PYTHON_BIN=$(which python$PYTHON_REQUIRED_MAJOR.$PYTHON_REQUIRED_MINOR 2>/dev/null || true)
+if [ -z "$PYTHON_BIN" ]; then
+  PYTHON_BIN=$(which python3)
+fi
+
 PYTHON_VER=$($PYTHON_BIN -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
 IFS='.' read -r CUR_MAJOR CUR_MINOR <<< "$PYTHON_VER"
 
 if [ "$CUR_MAJOR" -lt "$PYTHON_REQUIRED_MAJOR" ] || \
   { [ "$CUR_MAJOR" -eq "$PYTHON_REQUIRED_MAJOR" ] && \
     [ "$CUR_MINOR" -lt "$PYTHON_REQUIRED_MINOR" ]; }; then
-  echo "Python >= 3.10 is required. Found: $PYTHON_VER"
+  echo "Python >= $PYTHON_REQUIRED_MAJOR.$PYTHON_REQUIRED_MINOR is required."
+  echo "Found: $PYTHON_VER"
   exit 1
 fi
 echo "Found Python version $PYTHON_VER"
